#!/usr/bin/env bash

w_class=$2
w_id=$1
w_instance=$3
w_name="$(xprop -id $w_id _NET_WM_NAME)"


# ----------------------------------------
# Windows State
# ----------------------------------------

# Thunderbird About Window
if [[ "$w_name" =~ "About" ]]; then
  printf "state=floating"
fi

# Android Emulator
if [[ "$w_name" =~ "Android Emulator" ]]; then
  printf "state=floating"
fi

# ----------------------------------------
# Move to Desktop
# ----------------------------------------

if [[ "$w_class" =~ "Gimp" ]]; then
  printf "desktop=^4"
fi

if [[ "$w_class" =~ "Inkscape" ]]; then
  printf "desktop=^4"
fi
