#!/bin/bash
#
# Gimp class change for every version on Debian. So this is a workaround
# that let me use regex to move Gimp's window on the right desktop. Why?
# because bspwm rule's command doesn't support regex.

w_id=$1
w_class=$2
w_instance=$3

if [[ "$w_class" =~ "Gimp" ]]; then
  printf "desktop=^4"
fi
