#!/bin/bash
#
# Move to desktop rules for application that tends to change their class or
# instance or have convoluted one.

w_id=$1
w_class=$2
w_instance=$3

if [[ "$w_class" =~ "Gimp" ]]; then
  printf "desktop=^4"
fi

if [[ "$w_class" =~ "Inkscape" ]]; then
  printf "desktop=^4"
fi
