#!/bin/bash

# Set the window state depending on xprop properties.

w_id=$1
w_class=$2
w_instance=$3
# This works w/o quotes in a regular script.
w_name="$(xprop -id $w_id _NET_WM_NAME)"

# Thunderbird About Window
if [[ "$w_name" =~ "About" ]]; then
  printf "state=floating"
fi

# Android Emulator
if [[ "$w_name" =~ "Android Emulator" ]]; then
  printf "state=floating"
fi
