#!/bin/bash

# Set the window state depending on xprop properties.

w_id=$1
w_class=$2
w_instance=$3
# This works w/o quotes in a regular script.
w_name="$(xprop -id $w_id _NET_WM_NAME)"

# Thunderbird about page doesn't open as a floating window and we can't
# differenciate it by its window class or id. To fix this issue, we use
# xprop to get the _NET_WM_NAME and if it matches the Thunderbird about page
# one then we apply a floating state to it.
if [[ "$w_name" =~ "About" ]]; then
  printf "state=floating"
fi
