#!/usr/bin/bash

# Extend builtin cd function
LAST_DIR_FILE="/tmp/.lastdir"
cd() {
  # Go back nth directories (e.g `cd .. 5`)
	if [[ "$1" == ".." && -n "$2" ]]; then
    for (( i=$2; i>=1; i--)); do
		  builtin cd "$1"
    done
  else
    builtin cd "$@"
	fi
  # Save last directory we were in
  pwd > $LAST_DIR_FILE
}
# When opening a new terminal, set the last directory we were in
if [ -f "$LAST_DIR_FILE" ]; then
  cd "$(< $LAST_DIR_FILE)"
fi
