#!/usr/bin/env bash

# Theming
dnf install adwaita-qt4 adwaita-qt5

# Generate XDG folders
dnf install xdg-user-dirs
xdg-user-dirs-update

# Enable ssh-agent service
cd "$HOME/.dotfiles/user"
stow --target=$HOME services
systemctl enable --user ssh-agent.service
systemctl start --user ssh-agent.service

# Jekyll:
# Fix `error:/usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`
dnf install redhat-rpm-config

# Install Virt-Manager
#
# To install virtio drivers for Windows VM see:
# https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md
dnf install virt-manager
usermod -aG libvirt $WHOAMI

# Add /usr/local/lib(64) to $LD_LIBRARY_PATH
echo -e "/usr/local/lib\n/usr/local/lib64" >> /etc/ld.so.conf.d/usrlocal.conf
ldconfig -v
