#!/usr/bin/env bash

# ----------------------------------------
# Autostart
# ----------------------------------------

declare -A apps

apps=(
  [polybar]="polybar -r top"
)

# Detect if applications are already running. If not, start them.
for app in "${!apps[@]}"; do
  running="$(pgrep "$app")"

  if [[ ! "$running" ]]; then
    ${apps["$app"]} &
  fi
done

xrandr --output eDP-1 --scale 1.33
polybar-msg cmd restart

