alias grep='grep --color=auto'
alias ls='ls --group-directories-first --color=auto'
alias la='ls -a --group-directories-first'
alias lla='ls -lha --group-directories-first'
alias tree='tree -a --dirsfirst -I ".git|node_modules"'
alias webpy='python3 -m http.server 4000 --bind 127.0.0.1'
