#! /bin/sh

sxhkd &
polybar -r top &
feh --bg-scale /home/sdk/Pictures/Wallpapers/current.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config normal_border_color   "#4a4a4f"
bspc config focused_border_color  "#0a84ff"
bspc config window_gap            0

bspc config split_ratio           0.50
bspc config gapless_monocle       true

