#! /bin/sh

# Autostart

sxhkd &
polybar -r top &
feh --bg-scale /home/sdk/Pictures/Wallpapers/current.jpg
xsetroot -cursor_name left_ptr

# Global configurations

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config click_to_focus        true
bspc config focused_border_color  "#0a84ff"
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus     true
bspc config normal_border_color   "#4a4a4f"
bspc config split_ratio           0.50
bspc config window_gap            0

# Rules
#
# bspc rule -a <window class>:<window id> [options]
#
# List all WM with:
#   bspc wm -d

bspc rule -a "Firefox Developer Edition:Navigator"  desktop="^2"
bspc rule -a "Gimp-2.8:gimp-2.8"                    desktop="^5" 
bspc rule -a "Inkscape:inkscape"                    desktop="^5" 
bspc rule -a "Thunderbird:Mail"                     desktop="^4"
bspc rule -a "weechat:xterm"                        desktop="^3"
