#!/usr/bin/env bash 

# Set the window state depending on its type. By default, normal windows are 
# setted tiled and dialog are setted to floating
# 
# For a list of all window types see: 
#   https://standards.freedesktop.org/wm-spec/latest/ar01s05.html

if [[ "$(xwinfo -t $1)" == "normal" ]]; then
  printf "state=tiled"
elif [[ "$(xwinfo -t $1)" == "dialog" ]]; then
  printf "state=floating"
fi
