#!/usr/bin/env bash

# ---------------------------------------- 
# Autostart
# ---------------------------------------- 

declare -A apps

apps=(
  [polybar]="polybar -r top"
  [sxhkd]="sxhkd"
)

# Detect if applications are already running. If not, start them.
for app in "${!apps[@]}"; do
  running="$(pgrep "$app")"

  if [[ ! "$running" ]]; then
    ${apps["$app"]} &
  fi
done

feh --bg-scale /home/sdk/Pictures/wallpapers/current.jpg
xsetroot -cursor_name left_ptr

# ---------------------------------------- 
# bspwm 
# ---------------------------------------- 

# Global configurations

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config click_to_focus        button1
bspc config focused_border_color  "#0a84ff"
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus     true
bspc config initial_polarity      second_child
bspc config normal_border_color   "#4a4a4f"
bspc config split_ratio           0.50
bspc config window_gap            0

# Rules
#
# bspc rule -a <window class>:<window id> [options]
#
# List all WM with:
#   bspc wm -d

# clean rules list to avoid duplicate on config reload
bspc rule -r *:*

# Move to desktop
bspc rule -a Firefox      desktop="^2"
bspc rule -a Nightly      desktop="^2"
bspc rule -a Thunderbird  desktop="^3"
bspc rule -a Inkscape     desktop="^4" 

# External rules
bspc config external_rules_command ~/.config/bspwm/rules/bootstrap

