#!/usr/bin/env bash

# ----------------------------------------
# Autostart
# ----------------------------------------

declare -A apps

apps=(
  [polybar]="polybar -r top"
  [sxhkd]="sxhkd"
)

# Detect if applications are already running. If not, start them.
for app in "${!apps[@]}"; do
  running="$(pgrep "$app")"

  if [[ ! "$running" ]]; then
    ${apps["$app"]} &
  fi
done

# ----------------------------------------
# bspwm
# ----------------------------------------

# Colorscheme

declare -A colors

colors=(
  [blue]="#15539e"
  [grey-70]="#353535"
  [grey-80]="#2d2d2d"
  [grey-90]="#1b1b1b"
)

# Global configurations

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          	    2
bspc config click_to_focus        	    button1
#bspc config focused_border_color  	    "#0a84ff"
bspc config focused_border_color  	    "${colors["blue"]}"
bspc config gapless_monocle       	    true
bspc config ignore_ewmh_focus     	    true
bspc config initial_polarity      	    second_child
bspc config normal_border_color   	    "${colors["grey-70"]}"
bspc config remove_disabled_monitors 	  true
bspc config remove_unplugged_monitors 	true
bspc config split_ratio           	    0.50
bspc config window_gap            	    0

# Rules
#
# bspc rule -a <window class>:<window id> [options]
#
# List all WM with:
#   bspc wm -d

# clean rules list to avoid duplicate on config reload
bspc rule -r *:*

# Move to desktop
bspc rule -a *:Navigator        desktop="^2"
bspc rule -a Nightly            desktop="^2"
bspc rule -a Daily              desktop="^3"
bspc rule -a *:Mail             desktop="^3"
bspc rule -a discord            desktop="^4"
bspc rule -a Inkscape           desktop="^5"
bspc rule -a Steam              desktop="^6"

# Sticky windows
bspc rule -a Firefox:Toolkit sticky=on
bspc rule -a Nightly:Toolkit sticky=on

# Floating windows
bspc rule -a Firefox:Browser state=floating
bspc rule -a Firefox:Toolkit state=floating
bspc rule -a Nightly:Browser state=floating
bspc rule -a Nightly:Toolkit state=floating

# Misc rules
bspc rule -a Microsoft-edge-dev border=off
bspc rule -a "Microsoft Teams - Preview" border=off

# Temporary fix for Firefox starting as a floating window only in my main profile.
# I can reproduce it with mozregression...
bspc rule -a firefox-nightly:Navigator state=tiled

# External rules
bspc config external_rules_command ~/.config/bspwm/rules

